### ISSUE TITLE
What is the website link lol

### ISSUE THREAD

**Issue by xhendrikg** [dmonty2/server.properties#1]

**Comment by dmonty2** [comment]
I do not host it on a website.  You have to upload the php file to a web server that supports php on your own website.

**Comment by xhendrikg** [comment]
> 
> 
> I do not host it on a website. You have to upload the php file to a web server that supports php on your own website.

you maybe should say that in the readme. is the server.properties still uptodate?

**Comment by dmonty2** [comment]
Sorry if you don't own a web server then my project is not for you.  For
one-off minecraft servers it is best to edit the file itself using any text
editor.

Here is some documentation on what the options do.
https://minecraft.fandom.com/wiki/Server.properties
